name: pull-request-workflow

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run:  |
          cd structure-and-tests
          go build -v ./...

      - name: Test and coverage
        run: |
          cd structure-and-tests
          go test -coverage ./...
